services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=networkvisualizer.settings

  frontend:
    build:
      context: ./networkvisualizer
      dockerfile: Dockerfile.dev
    ports:
      - "4200:80"
    depends_on:
      - backend
