# Generated by Django 4.2.20 on 2025-04-23 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network_loading_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='graphsession',
            table='graph_session',
        ),
    ]
